### PR TITLE
Added bulk add api action on Participant class.

### PR DESCRIPTION
**Pull request by yjukaku**
For some reason, I'm getting a 500 error from the Challonge server - the work is basically done but I'm assuming I'm missing something tiny.  If necessary I can add some documentation to the README.

### CODE REVIEW

**Comment by akdarrah** [comment]
Hi @yjukaku , I'm trying to use the new `bulk_add` method and seeing an error. Can you show me how you were calling this method? Based on the code, this is what I was trying:

```
[1] pry(main)> Challonge::Participant.bulk_add(1248450, [{:name => "Test"}, {:name => "Test2"}])
ActiveResource::ServerError: Failed.  Response code = 500.  Response message = Internal Server Error.
from /Users/onebert/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/activeresource-3.2.17/lib/active_resource/connection.rb:148:in `handle_response'
```

**Comment by yjukaku** [comment]
@akdarrah Yep, that's how you are supposed to call it. I mentioned in the pull
request that I'm not sure why it's returning a 500 error - I figured that
you guys might be able to debug it better on a development machine.

**Comment by yjukaku** [comment]
Apologies if this isn't an accepted way to use pull requests - I don't GitHub
very often.

**Comment by akdarrah** [comment]
@yjukaku Ah, I missed that in your description initially.

I spent some time working on this tonight, and I got the success case working by passing the participants array through the second argument of `post` like this (I believe the third argument is for headers):

```
def self.bulk_add(tournament_id, participants_arrary)
  self.validated_post(:bulk_add, {tournament_id: tournament_id, participants: participants_arrary})
end
```

Which works fine by calling the method like before:

```
Challonge::Participant.bulk_add(1248450, [{:name => "Test"}, {:name => "Test2", :invite_name_or_email => "1bertlol"}])
```

The problem now is in the case that there is a validation error. In Challonge::API `self.validated_post` method we're referencing `errors`, but since we don't have an instance it's raising a NameError:

```
[1] pry(main)> Challonge::Participant.bulk_add(1248450, [{:name => "Test"}, {:name => "Test2", :invite_name_or_email => "1bertlol"}])
NameError: undefined local variable or method `errors' for Challonge::Participant:Class
from /Users/onebert/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/challonge-api-0.2.0/lib/challonge/api.rb:41:in `rescue in validated_post'
```

I'll have to think about how that _should_ be handled. Maybe we shouldn't be rescueing here at all. Any ideas? (Tagging @corneldm )

**Comment by yjukaku** [comment]
@akdarrah @corneldm A possible solution is to catch the error(s), create an array of blank participants, then set the errors attribute for each of those models.

I'm not sure how the errors response comes back from challonge''s bulk_add endpoint, but if it some sort of ordered list then it shouldn't be too hard, correct?

**Comment by yjukaku** [comment]
So I did some research into how Rails handles multiple record creation. It's basically the same notation:

```
Post.create([
  {title: "Hello", content: "Awesome content"},
  {title: "Hi", content: ""}
])
```

which then returns an array of Post objects that have the `Post#errors` attribute set.

Unfortunately it looks like the Challonge API doesn't return errors specific to each Participant, but rather a general 'error' message.  This is very far from ideal but still, what could be done is to add that general error as an error on every Participant object that the `#bulk_add` method would return.

**Pull request closed without merging**
